<?php

use Illuminate\Database\Seeder;

class StatsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('stats')->delete();
        
        \DB::table('stats')->insert(array (
            0 => 
            array (
                'id' => 383,
                'time' => 1555707600,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            1 => 
            array (
                'id' => 384,
                'time' => 1555708500,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            2 => 
            array (
                'id' => 385,
                'time' => 1555709400,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            3 => 
            array (
                'id' => 386,
                'time' => 1555710300,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            4 => 
            array (
                'id' => 387,
                'time' => 1555711200,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            5 => 
            array (
                'id' => 388,
                'time' => 1555712100,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            6 => 
            array (
                'id' => 389,
                'time' => 1555713000,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            7 => 
            array (
                'id' => 390,
                'time' => 1555713900,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            8 => 
            array (
                'id' => 391,
                'time' => 1555714800,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            9 => 
            array (
                'id' => 392,
                'time' => 1555715700,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            10 => 
            array (
                'id' => 393,
                'time' => 1555716600,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            11 => 
            array (
                'id' => 394,
                'time' => 1555717500,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            12 => 
            array (
                'id' => 395,
                'time' => 1555718400,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            13 => 
            array (
                'id' => 396,
                'time' => 1555719300,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            14 => 
            array (
                'id' => 397,
                'time' => 1555720200,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            15 => 
            array (
                'id' => 398,
                'time' => 1555721100,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            16 => 
            array (
                'id' => 399,
                'time' => 1555722000,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            17 => 
            array (
                'id' => 400,
                'time' => 1555722900,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            18 => 
            array (
                'id' => 401,
                'time' => 1555723800,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            19 => 
            array (
                'id' => 402,
                'time' => 1555724700,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            20 => 
            array (
                'id' => 403,
                'time' => 1555725600,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            21 => 
            array (
                'id' => 404,
                'time' => 1555726500,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            22 => 
            array (
                'id' => 405,
                'time' => 1555727400,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            23 => 
            array (
                'id' => 406,
                'time' => 1555728300,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            24 => 
            array (
                'id' => 407,
                'time' => 1555729200,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            25 => 
            array (
                'id' => 408,
                'time' => 1555730100,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            26 => 
            array (
                'id' => 409,
                'time' => 1555731000,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            27 => 
            array (
                'id' => 410,
                'time' => 1555731900,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            28 => 
            array (
                'id' => 411,
                'time' => 1555732800,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            29 => 
            array (
                'id' => 412,
                'time' => 1555733700,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            30 => 
            array (
                'id' => 413,
                'time' => 1555734600,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            31 => 
            array (
                'id' => 414,
                'time' => 1555735500,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            32 => 
            array (
                'id' => 415,
                'time' => 1555736400,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            33 => 
            array (
                'id' => 416,
                'time' => 1555737300,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            34 => 
            array (
                'id' => 417,
                'time' => 1555738200,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            35 => 
            array (
                'id' => 418,
                'time' => 1555739100,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            36 => 
            array (
                'id' => 419,
                'time' => 1555740000,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            37 => 
            array (
                'id' => 420,
                'time' => 1555740900,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            38 => 
            array (
                'id' => 421,
                'time' => 1555741800,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            39 => 
            array (
                'id' => 422,
                'time' => 1555742700,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            40 => 
            array (
                'id' => 423,
                'time' => 1555743600,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            41 => 
            array (
                'id' => 424,
                'time' => 1555744500,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            42 => 
            array (
                'id' => 425,
                'time' => 1555745400,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            43 => 
            array (
                'id' => 426,
                'time' => 1555746300,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            44 => 
            array (
                'id' => 427,
                'time' => 1555747200,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            45 => 
            array (
                'id' => 428,
                'time' => 1555748100,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            46 => 
            array (
                'id' => 429,
                'time' => 1555749000,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            47 => 
            array (
                'id' => 430,
                'time' => 1555749900,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            48 => 
            array (
                'id' => 431,
                'time' => 1555750800,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            49 => 
            array (
                'id' => 432,
                'time' => 1555751700,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            50 => 
            array (
                'id' => 433,
                'time' => 1555752600,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            51 => 
            array (
                'id' => 434,
                'time' => 1555753500,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            52 => 
            array (
                'id' => 435,
                'time' => 1555754400,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            53 => 
            array (
                'id' => 436,
                'time' => 1555755300,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            54 => 
            array (
                'id' => 437,
                'time' => 1555756200,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            55 => 
            array (
                'id' => 438,
                'time' => 1555757100,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            56 => 
            array (
                'id' => 439,
                'time' => 1555758000,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            57 => 
            array (
                'id' => 440,
                'time' => 1555758900,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            58 => 
            array (
                'id' => 441,
                'time' => 1555759800,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            59 => 
            array (
                'id' => 442,
                'time' => 1555760700,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            60 => 
            array (
                'id' => 443,
                'time' => 1555761600,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            61 => 
            array (
                'id' => 444,
                'time' => 1555762500,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            62 => 
            array (
                'id' => 445,
                'time' => 1555763400,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            63 => 
            array (
                'id' => 446,
                'time' => 1555764300,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            64 => 
            array (
                'id' => 447,
                'time' => 1555765200,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            65 => 
            array (
                'id' => 448,
                'time' => 1555766100,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            66 => 
            array (
                'id' => 449,
                'time' => 1555767000,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            67 => 
            array (
                'id' => 450,
                'time' => 1555767900,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            68 => 
            array (
                'id' => 451,
                'time' => 1555768800,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            69 => 
            array (
                'id' => 452,
                'time' => 1555769700,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            70 => 
            array (
                'id' => 453,
                'time' => 1555770600,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            71 => 
            array (
                'id' => 454,
                'time' => 1555771500,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            72 => 
            array (
                'id' => 455,
                'time' => 1555772400,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            73 => 
            array (
                'id' => 456,
                'time' => 1555773300,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            74 => 
            array (
                'id' => 457,
                'time' => 1555774200,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            75 => 
            array (
                'id' => 458,
                'time' => 1555775100,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            76 => 
            array (
                'id' => 459,
                'time' => 1555776000,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            77 => 
            array (
                'id' => 460,
                'time' => 1555776900,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            78 => 
            array (
                'id' => 461,
                'time' => 1555777800,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            79 => 
            array (
                'id' => 462,
                'time' => 1555778700,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            80 => 
            array (
                'id' => 463,
                'time' => 1555779600,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            81 => 
            array (
                'id' => 464,
                'time' => 1555780500,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            82 => 
            array (
                'id' => 465,
                'time' => 1555781400,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            83 => 
            array (
                'id' => 466,
                'time' => 1555782300,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            84 => 
            array (
                'id' => 467,
                'time' => 1555783200,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            85 => 
            array (
                'id' => 468,
                'time' => 1555784100,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            86 => 
            array (
                'id' => 469,
                'time' => 1555785000,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            87 => 
            array (
                'id' => 470,
                'time' => 1555785900,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            88 => 
            array (
                'id' => 471,
                'time' => 1555786800,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            89 => 
            array (
                'id' => 472,
                'time' => 1555787700,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            90 => 
            array (
                'id' => 473,
                'time' => 1555788600,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            91 => 
            array (
                'id' => 474,
                'time' => 1555789500,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            92 => 
            array (
                'id' => 475,
                'time' => 1555790400,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            93 => 
            array (
                'id' => 476,
                'time' => 1555791300,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            94 => 
            array (
                'id' => 477,
                'time' => 1555792200,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            95 => 
            array (
                'id' => 478,
                'time' => 1555793100,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            96 => 
            array (
                'id' => 479,
                'time' => 1555794000,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            97 => 
            array (
                'id' => 480,
                'time' => 1555794900,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            98 => 
            array (
                'id' => 481,
                'time' => 1555795800,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            99 => 
            array (
                'id' => 482,
                'time' => 1555796700,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            100 => 
            array (
                'id' => 483,
                'time' => 1555797600,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            101 => 
            array (
                'id' => 484,
                'time' => 1555798500,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            102 => 
            array (
                'id' => 485,
                'time' => 1555799400,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            103 => 
            array (
                'id' => 486,
                'time' => 1555800300,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            104 => 
            array (
                'id' => 487,
                'time' => 1555801200,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            105 => 
            array (
                'id' => 488,
                'time' => 1555802100,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            106 => 
            array (
                'id' => 489,
                'time' => 1555803000,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            107 => 
            array (
                'id' => 490,
                'time' => 1555803900,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            108 => 
            array (
                'id' => 491,
                'time' => 1555804800,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            109 => 
            array (
                'id' => 492,
                'time' => 1555805700,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            110 => 
            array (
                'id' => 493,
                'time' => 1555806600,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            111 => 
            array (
                'id' => 494,
                'time' => 1555807500,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            112 => 
            array (
                'id' => 495,
                'time' => 1555808400,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            113 => 
            array (
                'id' => 496,
                'time' => 1555809300,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            114 => 
            array (
                'id' => 497,
                'time' => 1555810200,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            115 => 
            array (
                'id' => 498,
                'time' => 1555811100,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            116 => 
            array (
                'id' => 499,
                'time' => 1555812000,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            117 => 
            array (
                'id' => 500,
                'time' => 1555812900,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            118 => 
            array (
                'id' => 501,
                'time' => 1555813800,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            119 => 
            array (
                'id' => 502,
                'time' => 1555814700,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
            120 => 
            array (
                'id' => 503,
                'time' => 1555815600,
                'profit' => 0.0,
                'wallet' => 0.0,
                'wallets' => NULL,
                'immature' => NULL,
                'margin' => 0.0,
                'waiting' => NULL,
                'balances' => 0.0,
                'onsell' => NULL,
                'renters' => NULL,
            ),
        ));
        
        
    }
}